### PR TITLE
removing BebopS file to prevent a -too many levels of symbolic links …

### PR DESCRIPTION
**Pull request by pcruiher08**
removing BebopS file to prevent a -too many levels of symbolic links issue- when trying to launch

### CODE REVIEW

**Comment by pcruiher08** [comment]
I mean folder, not file

**Comment by pcruiher08** [comment]
Actually, I do mean file, it appears to be a text file containing only "BebopS" which is causing a symbolic links issue

**Comment by gsilano** [comment]
Hi! Sorry, I did get the point of this pull request. Could you be more specific? Thanks!

**Comment by gsilano** [comment]
Closed for inactivity

**Pull request closed without merging**
